checks:
  addAllBuiltIn: true
  exclude:
    - "minimum-three-replicas"
    - "read-secret-from-env-var"
    - "required-annotation-email"
    - "required-label-owner"
    - "default-service-account"
    - "dnsconfig-options"
    - "no-node-affinity"
    - "non-isolated-pod"
    - "dangling-ingress"
