---
extends: default
rules:
  braces:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length: disable
  comments:
    min-spaces-from-content: 1
  truthy: disable
  document-start: disable
