repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: redis
    namespace: app
    chart: bitnami/redis
    version: 17.3.16
    values:
      - values.yaml
environments:
  dev: {}
  ci: {}
