architecture: standalone
auth:
  existingSecret: db-secret
  existingSecretPasswordKey: REDIS_PASSWORD
master:
  persistence:
    size: 1Gi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
