repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: promtail
    namespace: monitor
    chart: grafana/promtail
    version: 6.11.6
    values:
      - values.yaml
environments:
  dev: {}
  ci: {}
