---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public
  namespace: app
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/public
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
