repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: grafana
    namespace: monitor
    chart: grafana/grafana
    version: 6.60.5
    values:
      - values.yaml
environments:
  dev: {}
  ci: {}
