repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: mysql
    namespace: app
    chart: bitnami/mysql
    version: 9.4.5
    values:
      - values.yaml
environments:
  dev: {}
  ci: {}
