repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: kafka
    namespace: app
    chart: bitnami/kafka
    version: 20.0.1
    values:
      - values.yaml
environments:
  dev: {}
  ci: {}
