persistence:
  size: 1Gi
zookeeper:
  persistence:
    size: 1Gi
  containerSecurityContext:
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
