name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: aquaproj/aqua-installer@v2.1.2
        with:
          aqua_version: v2.12.2
      - id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            cmd/**
            internal/**
            .github/workflows/golangci-lint.yml
      - if: |
          steps.changed-files.outputs.any_changed == 'true' ||
          contains(github.event.pull_request.labels.*.name, 'golangci-lint')
        run: |
          golangci-lint run --out-format=github-actions
