name: golangci-lint
on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
  pull_request:
    branches:
      - master
    paths:
      - "backend/**"
jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.0.1
        with:
          aqua_version: v1.25.2
      - run: |
          cd backend
          golangci-lint run --out-format=github-actions
