name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: aquaproj/aqua-installer@v2.3.0
        with:
          aqua_version: v2.23.1
      - id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            cmd/**
            internal/**
            .github/workflows/golangci-lint.yml
      - if: |
          steps.changed-files.outputs.any_changed == 'true' ||
          contains(github.event.pull_request.labels.*.name, 'golangci-lint')
        run: |
          golangci-lint run
