name: yamllint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: |
            *.yaml
            *.yml
      - if: |
          steps.changed-files.outputs.any_changed == 'true'
        run: |
          yamllint -c .yamllint.yaml .
