name: yamllint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            *.yaml
            *.yml
      - if: |
          steps.changed-files.outputs.any_changed == 'true'
        run: |
          yamllint -c .yamllint.yaml .
