name: yamllint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files: |
            *.yaml
            *.yml
      - if: |
          steps.changed-files.outputs.any_changed == 'true'
        run: |
          yamllint -c .yamllint.yaml .
